title: TeenBook
description: Энциклопедия знаний
baseurl: "/2026_Teenbook"
url: "https://mrsbarul.github.io"

# Включаем папку WEB
include:
  - WEB

# Включаем обработку всех .md файлов
defaults:
  - scope:
      path: "WEB"
    values:
      layout: "article"

# Настройки Markdown
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md