@startmindmap
* Я и цифровой мир
** Моя зависимость
*** Экранное время
*** Скроллинг
*** Сон
*** Цифровой детокс
** Мои игры
*** Хобби
*** Киберспорт
*** Донаты
*** Сообщества
** Информационная гигиена
*** Фейки
*** Новости
*** Боты и тролли
*** Пузырь
** Безопасность в сети
*** Приватность
*** Публикации
*** Кибербуллинг
*** Цифровой след
** Реальность и виртуальность
*** Онлайн и офлайн
*** Виртуальная личность
*** FOMO
** Моя техника
*** Смартфон
*** Ноутбук
*** Ремонт
*** Апгрейд
@endmindmap
