%%{
    init: {
        'theme': 'base',
        'themeVariables': { 'fontSize': '18px' }
    }
}%%

graph LR
    n_21b16caca8["одиночество"]
    n_5ccce4c96a["социальные проблемы"]
    n_52404c662a["отрицательная эмоция"]
    n_fecb89cf61["Отчуждение"]
    n_ba82d27b1f["привязанность"]
    n_aa71140953["чувство"]
    n_03ca255886["социальная связь"]
    n_13f8be1bb9["социальная изоляция"]
    n_0663071cca["фактор риска"]
    n_897f868f61["психологический стресс"]
    n_913a43515f["Дистресс"]
    n_816094b634["человеческое поведение"]
    n_999de2910d["дружба"]
    n_de3009feb0["социальное дистанцирование"]

    n_21b16caca8 -- "это частный случай понятия" --> n_5ccce4c96a
    n_21b16caca8 -- "это частный случай понятия" --> n_52404c662a
    n_fecb89cf61 -- "это частный случай понятия" --> n_52404c662a
    n_ba82d27b1f -- "подкласс от" --> n_aa71140953
    n_03ca255886 -- "подкласс от" --> n_aa71140953
    n_13f8be1bb9 -- "подкласс от" --> n_0663071cca
    n_897f868f61 -- "подкласс от" --> n_0663071cca
    n_fecb89cf61 -- "подкласс от" --> n_5ccce4c96a
    n_913a43515f -- "подкласс от" --> n_897f868f61
    n_13f8be1bb9 -- "подкласс от" --> n_816094b634
    n_fecb89cf61 -- "подкласс от" --> n_913a43515f
    n_13f8be1bb9 -- "подкласс от" --> n_21b16caca8
    n_897f868f61 -- "подкласс от" --> n_52404c662a
    n_03ca255886 -- "противоположно" --> n_21b16caca8
    n_21b16caca8 -- "противоположно" --> n_03ca255886
    n_21b16caca8 -- "причиной является" --> n_21b16caca8
    n_21b16caca8 -- "вызывает" --> n_21b16caca8
    n_999de2910d -- "обладает свойством" --> n_ba82d27b1f
    n_de3009feb0 -- "не путать с" --> n_13f8be1bb9
    n_13f8be1bb9 -- "не путать с" --> n_de3009feb0