graph LR
  A[Компьютерная игра] --> B[Код]
  A --> C[Память (RAM)]
  
  D[Чит-код] --> E[Изменение кода]
  F[Трейнер] --> G[Изменение памяти]
  
  E --> B
  G --> C
  
  H[Исходный код] --> I[Модификации]
  I --> A