graph TD
  A[Кухня] --> B[Микроволновка]
  A --> C[Холодильник]
  A --> D[Чайник]
  
  B --> E[Электромагнитные волны]
  C --> F[Испарение/Конденсация]
  D --> G[Кипение]
  
  H[Дом] --> I[Лампочка]
  H --> J[Батарейка]
  
  I --> K[Нагрев нити]
  J --> L[Электрохимия]